//! Ownership of the user's `~/.bazelrc` via an idempotent managed region.
//!
//! fastverk owns only the marker-bracketed block; anything outside it is
//! preserved. This mirrors how `cli/fv/src/module.rs` edits a managed
//! region of `MODULE.bazel`. The generated block points Bazel at the
//! managed caches/registries and wires a single *unscoped*
//! `--credential_helper` at the fastverk cred-helper binary, which
//! self-routes by host via the connection registry.

use std::path::{Path, PathBuf};

use crate::config::Config;

pub const BEGIN: &str = "# >>> fastverk managed >>>";
pub const END: &str = "# <<< fastverk managed <<<";

/// Path to the installed cred-helper binary. Overridable via
/// `$FASTVERK_CRED_HELPER` (used in dev / tests). Default is the
/// install location inside the app bundle's helper dir.
#[must_use]
pub fn cred_helper_path() -> PathBuf {
    std::env::var("FASTVERK_CRED_HELPER").map_or_else(
        |_| PathBuf::from("/usr/local/bin/fastverk-cred-helper"),
        PathBuf::from,
    )
}

/// Render the fastverk-managed region of `~/.bazelrc` from config.
#[must_use]
pub fn managed_block(cfg: &Config, cred_helper: &Path) -> String {
    let mut out = String::new();
    out.push_str(BEGIN);
    out.push('\n');
    out.push_str("# Generated by fastverk. Edits inside this block are overwritten.\n");
    out.push_str(&format!(
        "startup --output_user_root={}\n",
        cfg.output_user_root.display()
    ));
    out.push_str("common --enable_bzlmod\n");
    for reg in &cfg.registries {
        out.push_str(&format!("common --registry={reg}\n"));
    }
    out.push_str(&format!(
        "common --credential_helper={}\n",
        cred_helper.display()
    ));
    out.push_str(&format!("build --disk_cache={}\n", cfg.disk_cache.display()));
    out.push_str(END);
    out.push('\n');
    out
}

/// Splice `block` into an existing `~/.bazelrc` body, replacing any prior
/// managed region and preserving everything else. Appends when absent.
#[must_use]
pub fn splice(existing: &str, block: &str) -> String {
    if let (Some(b), Some(e)) = (existing.find(BEGIN), existing.find(END)) {
        let e_end = e + END.len();
        let mut s = String::with_capacity(existing.len() + block.len());
        s.push_str(&existing[..b]);
        s.push_str(block.trim_end_matches('\n'));
        s.push_str(&existing[e_end..]);
        s
    } else {
        let mut s = existing.to_string();
        if !s.is_empty() && !s.ends_with('\n') {
            s.push('\n');
        }
        if !s.is_empty() {
            s.push('\n');
        }
        s.push_str(block);
        s
    }
}

#[cfg(test)]
mod tests {
    use super::{managed_block, splice, BEGIN, END};
    use crate::config::Config;
    use std::path::Path;

    #[test]
    fn block_is_bracketed_and_has_cred_helper() {
        let b = managed_block(&Config::default(), Path::new("/x/cred-helper"));
        assert!(b.starts_with(BEGIN));
        assert!(b.contains("--credential_helper=/x/cred-helper"));
        assert!(b.trim_end().ends_with(END));
    }

    #[test]
    fn splice_is_idempotent() {
        let block = managed_block(&Config::default(), Path::new("/x/ch"));
        let once = splice("# user line\n", &block);
        let twice = splice(&once, &block);
        assert_eq!(once, twice);
        assert!(once.starts_with("# user line"));
    }
}
