//! Ownership of the user's `~/.bazelrc` via an idempotent managed region.
//!
//! fastverk owns only the marker-bracketed block; anything outside it is
//! preserved. This mirrors how `cli/fv/src/module.rs` edits a managed
//! region of `MODULE.bazel`. The generated block points Bazel at the
//! managed caches/registries and wires a single *unscoped*
//! `--credential_helper` at the fastverk cred-helper binary, which
//! self-routes by host via the connection registry.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::config::Config;
use crate::paths;

pub const BEGIN: &str = "# >>> fastverk managed >>>";
pub const END: &str = "# <<< fastverk managed <<<";

/// Path to the installed cred-helper binary. Overridable via
/// `$FASTVERK_CRED_HELPER`. Defaults to a user-writable location
/// (`~/.local/bin/fastverk-cred-helper`) so install needs no sudo.
#[must_use]
pub fn cred_helper_path() -> PathBuf {
    if let Ok(p) = std::env::var("FASTVERK_CRED_HELPER") {
        return PathBuf::from(p);
    }
    directories::BaseDirs::new().map_or_else(
        || PathBuf::from("/usr/local/bin/fastverk-cred-helper"),
        |d| d.home_dir().join(".local/bin/fastverk-cred-helper"),
    )
}

/// Render the fastverk-managed region of `~/.bazelrc` from config.
#[must_use]
pub fn managed_block(cfg: &Config, cred_helper: &Path) -> String {
    let mut out = String::new();
    out.push_str(BEGIN);
    out.push('\n');
    out.push_str("# Generated by fastverk. Edits inside this block are overwritten.\n");
    out.push_str(&format!(
        "startup --output_user_root={}\n",
        cfg.output_user_root.display()
    ));
    out.push_str("common --enable_bzlmod\n");
    for reg in &cfg.registries {
        out.push_str(&format!("common --registry={reg}\n"));
    }
    out.push_str(&format!(
        "common --credential_helper={}\n",
        cred_helper.display()
    ));
    out.push_str(&format!("build --disk_cache={}\n", cfg.disk_cache.display()));
    out.push_str(END);
    out.push('\n');
    out
}

/// Splice `block` into an existing `~/.bazelrc` body, replacing any prior
/// managed region and preserving everything else. Appends when absent.
#[must_use]
pub fn splice(existing: &str, block: &str) -> String {
    if let (Some(b), Some(e)) = (existing.find(BEGIN), existing.find(END)) {
        let e_end = e + END.len();
        let mut s = String::with_capacity(existing.len() + block.len());
        s.push_str(&existing[..b]);
        s.push_str(block.trim_end_matches('\n'));
        s.push_str(&existing[e_end..]);
        s
    } else {
        let mut s = existing.to_string();
        if !s.is_empty() && !s.ends_with('\n') {
            s.push('\n');
        }
        if !s.is_empty() {
            s.push('\n');
        }
        s.push_str(block);
        s
    }
}

/// The fastverk-managed region of `s`, markers included, if present.
fn extract_region(s: &str) -> Option<&str> {
    let b = s.find(BEGIN)?;
    let e = s.find(END)? + END.len();
    Some(&s[b..e])
}

/// A simple `-old / +new` diff of just the managed region (we replace the
/// whole region, so a region-level diff is the honest representation).
#[must_use]
pub fn region_diff(existing: &str, new_block: &str) -> String {
    let mut d = String::new();
    if let Some(old) = extract_region(existing) {
        for l in old.lines() {
            d.push_str("- ");
            d.push_str(l);
            d.push('\n');
        }
    }
    for l in new_block.trim_end_matches('\n').lines() {
        d.push_str("+ ");
        d.push_str(l);
        d.push('\n');
    }
    d
}

/// Splice the managed region into `~/.bazelrc`, preserving everything
/// outside it. Returns `(changed, region-diff)`. When `validate_only`,
/// computes without writing.
pub fn apply(cfg: &Config, cred_helper: &Path, validate_only: bool) -> Result<(bool, String)> {
    let path = paths::user_bazelrc()?;
    let existing = std::fs::read_to_string(&path).unwrap_or_default();
    let block = managed_block(cfg, cred_helper);
    let updated = splice(&existing, &block);
    let changed = updated != existing;
    let diff = if changed {
        region_diff(&existing, &block)
    } else {
        String::new()
    };
    if changed && !validate_only {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).ok();
        }
        std::fs::write(&path, &updated).with_context(|| format!("write {}", path.display()))?;
    }
    Ok((changed, diff))
}

#[cfg(test)]
mod tests {
    use super::{managed_block, region_diff, splice, BEGIN, END};
    use crate::config::Config;
    use std::path::Path;

    #[test]
    fn block_is_bracketed_and_has_cred_helper() {
        let b = managed_block(&Config::default(), Path::new("/x/cred-helper"));
        assert!(b.starts_with(BEGIN));
        assert!(b.contains("--credential_helper=/x/cred-helper"));
        assert!(b.trim_end().ends_with(END));
    }

    #[test]
    fn splice_is_idempotent() {
        let block = managed_block(&Config::default(), Path::new("/x/ch"));
        let once = splice("# user line\n", &block);
        let twice = splice(&once, &block);
        assert_eq!(once, twice);
        assert!(once.starts_with("# user line"));
    }

    #[test]
    fn region_diff_replaces_whole_region() {
        let block = managed_block(&Config::default(), Path::new("/x/ch"));
        // No prior region: only additions.
        let d = region_diff("# user\n", &block);
        assert!(d.lines().all(|l| l.starts_with("+ ")));
        // Prior region present: both removals and additions.
        let with = splice("# user\n", &managed_block(&Config::default(), Path::new("/old")));
        let d2 = region_diff(&with, &block);
        assert!(d2.contains("- # >>> fastverk managed >>>"));
        assert!(d2.contains("+ # >>> fastverk managed >>>"));
    }
}
